#!/bin/bash

# Clean up previous builds
rm -rf evaLexer.h evaGrammar.yy.c evaGrammar.c evaGrammar.o evaGrammar.yy.o evaLLM.o eva-llvm eva-llvm-debug eva.ll

# Generate lexer and parser source files
flex -o evaGrammar.yy.c evaLex.l
bison -d -o evaGrammar.c evaGrammar.y


# Check if the build is for debug
if [ "$1" == "debug" ]; then
    echo "Building in debug mode with DEBUG_MAIN macro defined"

    # Compile the generated lexer and parser
    clang++ -std=c++20 -c evaGrammar.c evaGrammar.yy.c evaParser.cpp -DDEBUG_MAIN
    
    clang++ -std=c++20 -o eva-llvm -std=c++17 -stdlib=libc++ evaGrammar.o evaGrammar.yy.o evaParser.o -ll -g
else
    echo "Building in regular mode without DEBUG_MAIN macro"
    # Compile the generated lexer and parser
    clang++ -std=c++20 -c evaGrammar.c evaGrammar.yy.c evaParser.cpp
    
    clang++ -std=c++20 -o eva-llvm -I/opt/homebrew/Cellar/llvm/18.1.5/include -std=c++17 -stdlib=libc++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -L/opt/homebrew/Cellar/llvm/18.1.5/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names -lLLVM-18 evaGrammar.o evaGrammar.yy.o evaParser.o evaLLM.cpp -ll -g
fi
